// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Monster_Collector.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240527030816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedColumns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Monster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = "bf9f5481-2715-40cb-9300-d1d8cf8af261",
                            Attack = 47,
                            Defense = 20,
                            Description = "A big scary Goblin",
                            Health = 94,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = "cc73bc38-e059-4b73-bbad-d89a42dd8bba",
                            Attack = 26,
                            Defense = 21,
                            Description = "A big scary Dragon",
                            Health = 33,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = "c14e59db-1478-49c7-80a1-9e5850771d8d",
                            Attack = 43,
                            Defense = 25,
                            Description = "A big scary Ogre",
                            Health = 91,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "6bc823a2-793f-4445-ae45-9a839fe6089a",
                            Attack = 32,
                            Defense = 23,
                            Description = "A big scary Demon",
                            Health = 45,
                            Name = "Demon"
                        },
                        new
                        {
                            Id = "d0012337-b68e-42fa-bca7-7e41d07a815d",
                            Attack = 49,
                            Defense = 6,
                            Description = "A big scary Troll",
                            Health = 22,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = "70509de8-0ce9-43fb-92b9-5cd9027933ff",
                            Attack = 25,
                            Defense = 9,
                            Description = "A big scary Dragon",
                            Health = 80,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = "e27a46b2-cb7a-49bb-bde2-74659bbc3f43",
                            Attack = 15,
                            Defense = 18,
                            Description = "A big scary Goblin",
                            Health = 55,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = "0191aef6-f7e8-45e1-9212-564e6b4d2eb5",
                            Attack = 45,
                            Defense = 17,
                            Description = "A big scary Goblin",
                            Health = 89,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = "5a6adbc0-3d93-48a1-8170-6c955bf10a53",
                            Attack = 50,
                            Defense = 24,
                            Description = "A big scary Troll",
                            Health = 90,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = "7e26a7e3-d516-43f2-ad46-79360aec5fb0",
                            Attack = 26,
                            Defense = 7,
                            Description = "A big scary Dragon",
                            Health = 68,
                            Name = "Dragon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
