// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Monster_Collector.Migrations
{
    [DbContext(typeof(MonsterContext))]
    [Migration("20240526213739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Monster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = "62f6e0d5-5c6e-4eee-934d-0b7e33e84dda",
                            Attack = 43,
                            Defense = 15,
                            Description = "A big scary Dragon",
                            Health = 92,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = "ddd65601-f0bd-411c-8a3a-8873a2a3a4e8",
                            Attack = 44,
                            Defense = 12,
                            Description = "A big scary Dragon",
                            Health = 79,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = "6d1ba26e-e820-4c40-9225-22e947c3ca9a",
                            Attack = 45,
                            Defense = 7,
                            Description = "A big scary Ogre",
                            Health = 90,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "5d5ee1ac-1f91-4261-9e18-bf1d12c1ec22",
                            Attack = 33,
                            Defense = 6,
                            Description = "A big scary Ogre",
                            Health = 44,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "3e3cd1f4-6d47-4fee-a6f5-7db18a02d8d5",
                            Attack = 26,
                            Defense = 18,
                            Description = "A big scary Troll",
                            Health = 68,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = "b988d987-0f42-47b2-8962-7183c2ebb4e4",
                            Attack = 26,
                            Defense = 12,
                            Description = "A big scary Demon",
                            Health = 79,
                            Name = "Demon"
                        },
                        new
                        {
                            Id = "8f3c3796-6a1c-48db-8aeb-05aa1340aba4",
                            Attack = 17,
                            Defense = 15,
                            Description = "A big scary Ogre",
                            Health = 64,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "f32f7866-07d0-41c5-be7d-b25d9079408f",
                            Attack = 35,
                            Defense = 18,
                            Description = "A big scary Goblin",
                            Health = 42,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = "6f4442d9-36c8-4c78-ae21-a0c5c54e3f6a",
                            Attack = 27,
                            Defense = 10,
                            Description = "A big scary Demon",
                            Health = 66,
                            Name = "Demon"
                        },
                        new
                        {
                            Id = "3249c1ae-2b14-4374-8c09-cefdb403fe89",
                            Attack = 44,
                            Defense = 13,
                            Description = "A big scary Troll",
                            Health = 43,
                            Name = "Troll"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
