// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Monster_Collector.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedColumns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Monster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = "93e6cb95-f3c5-4395-b97a-6aad1bf4b209",
                            Attack = 45,
                            Defense = 16,
                            Description = "A big scary Demon",
                            Health = 91,
                            Name = "Demon"
                        },
                        new
                        {
                            Id = "86b49eb9-ad59-43bb-962b-c000d6890dad",
                            Attack = 24,
                            Defense = 20,
                            Description = "A big scary Troll",
                            Health = 61,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = "35e61d33-ef38-437c-8f98-7f14e913da96",
                            Attack = 39,
                            Defense = 14,
                            Description = "A big scary Dragon",
                            Health = 98,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = "5057a8fc-1677-46fa-abe8-f14fd47fb845",
                            Attack = 10,
                            Defense = 15,
                            Description = "A big scary Dragon",
                            Health = 63,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = "ed34e5e1-ddce-4e63-a300-015de6bab7f1",
                            Attack = 34,
                            Defense = 11,
                            Description = "A big scary Troll",
                            Health = 86,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = "682fb900-b1e7-4ff1-8a58-ce689121051d",
                            Attack = 45,
                            Defense = 13,
                            Description = "A big scary Goblin",
                            Health = 52,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = "ada29946-39ad-4d2b-afb6-fc9206eaeded",
                            Attack = 28,
                            Defense = 9,
                            Description = "A big scary Ogre",
                            Health = 75,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "f4cc6398-b37d-4fe8-85b1-47c56bbe60c1",
                            Attack = 23,
                            Defense = 22,
                            Description = "A big scary Ogre",
                            Health = 74,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "06e5397e-c8f4-468e-8105-154448a0d5c6",
                            Attack = 22,
                            Defense = 10,
                            Description = "A big scary Goblin",
                            Health = 58,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = "27e7d817-f023-4041-ad44-d090c8c7d6f6",
                            Attack = 46,
                            Defense = 7,
                            Description = "A big scary Ogre",
                            Health = 80,
                            Name = "Ogre"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
