// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Monster_Collector.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActionType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChangedColumns")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateChanged")
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("Monster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = "b69d832e-b04a-49e1-a0d7-a6885eb798d2",
                            Attack = 10,
                            Defense = 12,
                            Description = "A big scary Troll",
                            Health = 59,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = "6bfa80d7-c5d6-427e-8dd6-4370bea8ee94",
                            Attack = 34,
                            Defense = 6,
                            Description = "A big scary Ogre",
                            Health = 69,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "8f2341ef-aa83-4a93-81fd-31962adda1f4",
                            Attack = 35,
                            Defense = 21,
                            Description = "A big scary Goblin",
                            Health = 80,
                            Name = "Goblin"
                        },
                        new
                        {
                            Id = "a390051d-b53e-4a12-9c5c-d257024f37ab",
                            Attack = 40,
                            Defense = 8,
                            Description = "A big scary Troll",
                            Health = 81,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = "9546bf54-f4c5-48fd-aaf9-df59edca3af1",
                            Attack = 45,
                            Defense = 16,
                            Description = "A big scary Troll",
                            Health = 82,
                            Name = "Troll"
                        },
                        new
                        {
                            Id = "cc7c19d6-f08b-419e-80e8-1cfb05aa8d22",
                            Attack = 21,
                            Defense = 19,
                            Description = "A big scary Dragon",
                            Health = 59,
                            Name = "Dragon"
                        },
                        new
                        {
                            Id = "e7e03c0d-270a-4c5a-9bfc-69a534efee85",
                            Attack = 35,
                            Defense = 6,
                            Description = "A big scary Demon",
                            Health = 51,
                            Name = "Demon"
                        },
                        new
                        {
                            Id = "06706ea4-5fa8-40cb-91b7-f316ad4011e5",
                            Attack = 27,
                            Defense = 19,
                            Description = "A big scary Ogre",
                            Health = 76,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "df2bf1af-e150-443b-b312-af5a31524939",
                            Attack = 32,
                            Defense = 5,
                            Description = "A big scary Ogre",
                            Health = 77,
                            Name = "Ogre"
                        },
                        new
                        {
                            Id = "fb0faf97-9751-4ac2-ab74-85a51081d186",
                            Attack = 37,
                            Defense = 13,
                            Description = "A big scary Demon",
                            Health = 78,
                            Name = "Demon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
